---
abstract: 'NetAddr::IP related types and coercions for Moose'
author:
  - 'Todd Caine <todd.caine@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-NetAddr-IP
no_index:
  directory:
    - t
    - inc
requires:
  Class::Load: 0.2
  Moose: 0.41
  MooseX::Types: 0.19
  NetAddr::IP: 0
  Test::Exception: 0
  namespace::clean: 0.08
version: 0.06
