--- #YAML:1.0
name:               MooseX-Types-NetAddr-IP
version:            0.01
abstract:           NetAddr::IP related types and coercions for Moose
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:             0.41
    MooseX::Types:     0.19
    namespace::clean:  0.08
    NetAddr::IP:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
